function configdisp = importfile_cohere_disp(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CONFIGDISP = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a cell array.
%
%  CONFIGDISP = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  configdisp = importfile("/home/dzhigd/work/projects/PerovskiteSolarCells/Experiments/APS-34IDC/19112020/analysis/19112020_622-630/conf/config_disp", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2021 17:33:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["results_dir", "VarName2", "homedzhigdworkprojectsPerovskiteSolarCellsExperimentsAPS34IDC19"];
opts.VariableTypes = ["char", "char", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["results_dir", "VarName2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["results_dir", "VarName2"], "EmptyFieldRule", "auto");

% Import the data
configdisp = readtable(filename, opts);

%% Convert to output type
configdisp = table2cell(configdisp);
numIdx = cellfun(@(x) ~isnan(str2double(x)), configdisp);
configdisp(numIdx) = cellfun(@(x) {str2double(x)}, configdisp(numIdx));
end